SETTINGS_UPDATE_RATE="update_rate"
DEFAULT_UPDATE_RATE="LOW"

SETTINGS_CONN_CHANNEL="conn_channel"
DEFAULT_CONN_CHANNEL="USB"

SETTINGS_FIRMWARE="firmware"
DEFAULT_FIRMWARE="intensity_tracing_usb.flim"

SETTINGS_BIN_WIDTH_MICROS="bin_width_micros"
DEFAULT_BIN_WIDTH_MICROS=1000

SETTINGS_TIME_SPAN="time_span"
DEFAULT_TIME_SPAN=5

SETTINGS_ACQUISITION_TIME_MILLIS="acquisition_time_millis"
DEFAULT_ACQUISITION_TIME_MILLIS=None

SETTINGS_DRAW_FREQUENCY="draw_frequency"
DEFAULT_DRAW_FREQUENCY=10

SETTINGS_FREE_RUNNING_MODE="running_mode"
DEFAULT_FREE_RUNNING_MODE=True

SETTINGS_WRITE_DATA="write_data"
DEFAULT_WRITE_DATA=True

SETTINGS_ENABLED_CHANNELS="enabled_channels"
DEFAULT_ENABLED_CHANNELS=[0]

SETTINGS_SHOW_CPS="show_cps"
DEFAULT_SHOW_CPS=False